#' Available modules
#'
#' @description
#' Lists the modules that are available in a `grr` map made from a template.
#'
#' @param map Name of a `grr` map generated by `create_from_template()`.
#' @return A S3 object of class `grr` built upon a list.
#' @export
available_modules <- function(map) {
    map$template$available_modules
}


